apiVersion: v1
kind: Namespace
metadata:
  name: kubelego
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelego
  namespace: kubelego
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubelego
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelego
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubelego
subjects:
  - kind: ServiceAccount
    name: kubelego
    namespace: kubelego
